version: '3'

services:

  config-server:
    container_name: config-server
    hostname: config-service
    build:
      context: ./config-server/
      dockerfile: Dockerfile
    image: config-server:latest
    restart: on-failure
    expose:
      - 8888
    ports:
      - 8888:8888

  eureka-server:
    container_name: eureka-server
    hostname: eureka-server
    build:
      context: ./eureka-service/
      dockerfile: Dockerfile
    image: eureka-server:latest
    restart: on-failure
    expose:
      - 8761
    ports:
      - 8761:8761
    depends_on:
      - config-server

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway/
      dockerfile: Dockerfile
    image: api-gateway:latest
    restart: on-failure
    environment:
      - EUREKA_SERVER=http://eureka-server:8761/eureka
      - CONFIG_SERVER=http://config-server:8888
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - eureka-server
      - config-server

  system-events:
    container_name: system-events
    build:
      context: ./system-events/
      dockerfile: Dockerfile
    image: system-events:latest
    restart: on-failure
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=events
      - EUREKA_SERVER=http://eureka-server:8761/eureka
      - CONFIG_SERVER=http://config-server:8888
    expose:
      - 9190
    ports:
      - 9190:9190
    depends_on:
      - eureka-server
      - mysql
      - config-server

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=events
      - MYSQL_USER=nwttim3
      - MYSQL_PASSWORD=password
    ports:
      - 33061:3306

  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service/
      dockerfile: Dockerfile
    image: auth-service:latest
    restart: on-failure
    environment:
      - DB_HOST=mysql-auth
      - DB_PORT=3306
      - DB_NAME=jwt_service
      - EUREKA_SERVER=http://eureka-server:8761/eureka
      - CONFIG_SERVER=http://config-server:8888
    expose:
      - 8090  # Expose the port that your authentication service is running on
    ports:
      - 8090:8090  # Map the port to a port on your host
    depends_on:
      - eureka-server
      - mysql-auth
      - config-server

  mysql-auth:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=jwt_service
      - MYSQL_USER=nwttim3  # Your MySQL user for the authentication service
      - MYSQL_PASSWORD=password  # Your MySQL password for the authentication service
    ports:
      - 33062:3306

  election-service:
    container_name: election-service
    build:
      context: ./election-management/
      dockerfile: Dockerfile
    image: election-service:latest
    restart: on-failure
    environment:
      - DB_HOST=mysql-election
      - DB_PORT=3306
      - DB_NAME=election
      - EUREKA_SERVER=http://eureka-server:8761/eureka
      - CONFIG_SERVER=http://config-server:8888
    expose:
      - 8089  # Expose the port that your authentication service is running on
    ports:
      - 8089:8089  # Map the port to a port on your host
    depends_on:
      - eureka-server
      - mysql-election
      - config-server

  mysql-election:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=election
      - MYSQL_USER=nwttim3  
      - MYSQL_PASSWORD=password
    ports:
      - 33063:3306


  voting-service:
    container_name: voting-service
    image: voting-service:latest
    build:
      context: ./voting-service/
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - DB_HOST=mysql-voting
      - DB_PORT=3306
      - DB_NAME=voterdb
      - EUREKA_SERVER=http://eureka-server:8761/eureka
      - CONFIG_SERVER=http://config-server:8888
    expose:
      - 8082  # Expose the port that your authentication service is running on
    ports:
      - 8082:8082  # Map the port to a port on your host
    depends_on:
      - eureka-server
      - mysql-voting
      - config-server

  mysql-voting:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=voterdb
      - MYSQL_USER=nwttim3  
      - MYSQL_PASSWORD=password
    ports:
      - 33064:3306

  result-service:
    container_name: result-service
    image: result-service:latest
    build:
      context: ./result-service/
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - DB_HOST=mysql-result
      - DB_PORT=3306
      - DB_NAME=resultdb
      - EUREKA_SERVER=http://eureka-server:8761/eureka
      - CONFIG_SERVER=http://config-server:8888
    expose:
      - 8081  # Expose the port that your authentication service is running on
    ports:
      - 8081:8081  # Map the port to a port on your host
    depends_on:
      - eureka-server
      - mysql-result
      - config-server

  mysql-result:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=resultdb
      - MYSQL_USER=nwttim3  
      - MYSQL_PASSWORD=password
    ports:
      - 33065:3306    
    
